apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-init
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-system:node-init
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - watch
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-system:node-init
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-system:node-init
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: node-init
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-init
  namespace: kube-system
  labels:
    app: node-init
spec:
  selector:
    matchLabels:
      app: node-init
  template:
    metadata:
      labels:
        app: node-init
    spec:
      serviceAccountName: node-init
      containers:
      - name: node-init
        image: ghcr.io/metal-stack/node-init:latest
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
      hostNetwork: true
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
